### ISSUE TITLE
npm ERR! Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by mtzfactory** [react-native-enable-debug-in-release/react-native-enable-debug-in-release#4]
I'm getting the following error when I run the command:

```
❯ npx react-native-enable-debug-in-release
npm ERR! Cannot convert undefined or null to object

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2021-04-14T17_18_54_295Z-debug.log
```

This is the log:

```
0 verbose cli [
0 verbose cli   '/usr/local/bin/node',
0 verbose cli   '/usr/local/lib/node_modules/npm/bin/npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   'react-native-enable-debug-in-release'
0 verbose cli ]
1 info using npm@7.0.14
2 info using node@v12.13.1
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 3ms
5 timing config:load:builtin Completed in 3ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:/Users/xxx/yyy/development/apps/zzz/.npmrc Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:/xxx/yyy/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 9ms
19 verbose npm-session e351480bc6d69036
20 timing npm:load Completed in 29ms
21 http fetch GET 200 https://registry.npmjs.org/react-native-enable-debug-in-release 1048ms
22 timing command:exec Completed in 1062ms
23 verbose stack TypeError: Cannot convert undefined or null to object
23 verbose stack     at Function.keys (<anonymous>)
23 verbose stack     at module.exports (/usr/local/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:211:22)
23 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/pacote/lib/registry.js:96:26
23 verbose stack     at async /usr/local/lib/node_modules/npm/lib/exec.js:152:12
23 verbose stack     at async Promise.all (index 0)
23 verbose stack     at async exec (/usr/local/lib/node_modules/npm/lib/exec.js:143:17)
24 verbose cwd /Users/xxx/yyy/development/apps/zzz
25 verbose Darwin 20.3.0
26 verbose argv "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "exec" "--" "react-native-enable-debug-in-release"
27 verbose node v12.13.1
28 verbose npm  v7.0.14
29 error Cannot convert undefined or null to object
30 verbose exit 1
```

**Comment by bolan9999** [comment]
any updates ?
